title: My Custom Theme
description: A beautiful custom theme for GitHub Pages
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Navigation
nav_links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Blog
    url: /blog/
  - title: Contact
    url: /contact/
